import "../styles/QualityFilter.css";
import { Globe,Users,Shield,Zap} from "lucide-react";

export default function QualityFilter() {
  const filters = [
    {
      label: "RAW ENGINE OUTPUT",
      title: "Ideas Generated by Engine",
      percent: "100%",
    },
    {
      label: "MIN $1B TAM",
      title: "Pass Initial Market Filter",
      percent: "41%",
    },
    {
      label: "CLEAR MOAT EXISTS",
      title: "Pass Competitive Analysis",
      percent: "31%",
    },
    {
      label: "EXECUTION-READY",
      title: "Analyst-Approved & Delivered",
      percent: "23%",
      active: true,
    },
  ];

  const stats = [
    {
      icon: <Globe size={28} />,
      title: "40,000+",
      text: "market signals per idea",
    },
    {
      icon: <Users size={28} />,
      title: "12+ analysts",
      text: "covering every sector",
    },
    {
      icon: <Shield size={28} />,
      title: "100% unique",
      text: "no two users get the same idea",
    },
    {
      icon: <Zap size={28} />,
      title: "48 hrs",
      text: "analyst turnaround time",
    },
  ];

  return (
    <section className="quality-filter">
      <div className="quality-container">

        <p className="quality-tag">QUALITY FILTER</p>

        <h2 className="quality-title">
          Only 23% of ideas make it through to you.
        </h2>

        <p className="quality-description">
          Our engine generates many. Our analysts approve few.
          What reaches your dashboard has passed a rigorous gauntlet.
        </p>

        <div className="cards-row">
          {filters.map((item, index) => (
            <div className="card-wrapper" key={index}>
              <div
                className={`filter-card ${
                  item.active ? "active-card" : ""
                }`}
              >
                <span className="small-label">
                  {item.label}
                </span>

                <h3>{item.title}</h3>

                <div
                  className={`percentage ${
                    item.active ? "gold" : ""
                  }`}
                >
                  {item.percent}
                </div>
              </div>

              {index !== filters.length - 1 && (
                <div className="arrow">→</div>
              )}
            </div>
          ))}
        </div>

        <p className="bottom-copy">
          Only 23 out of every 100 ideas our engine generates survive analyst
          review—so what reaches you is genuinely differentiated.
        </p>

        <div className="stats-grid">
          {stats.map((item, index) => (
            <div className="stat-card" key={index}>
              <div className="icon-box">
                {item.icon}
              </div>

              <h4>{item.title}</h4>

              <p>{item.text}</p>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}